SELECT
    HACKERS.HACKER_ID,
    HACKERS.NAME,
    SUM(SCORES.MAX_SCORE)
FROM (
        SELECT
            HACKER_ID,
            CHALLENGE_ID,
            MAX(SCORE) AS MAX_SCORE
        FROM SUBMISSIONS
        GROUP BY
            CHALLENGE_ID,
            HACKER_ID
    ) AS SCORES
    INNER JOIN HACKERS ON SCORES.HACKER_ID = HACKERS.HACKER_ID
GROUP BY
    HACKERS.HACKER_ID,
    HACKERS.NAME
HAVING
    SUM(SCORES.MAX_SCORE) > 0
ORDER BY
    SUM(SCORES.MAX_SCORE) DESC,
    HACKERS.HACKER_ID ASC;