SELECT
    IF(G.GRADE >= 8, S.NAME, NULL),
    G.GRADE,
    S.MARKS
FROM STUDENTS S
    INNER JOIN GRADES G ON S.MARKS BETWEEN MIN_MARK AND MAX_MARK
ORDER BY
    G.GRADE DESC,
    S.NAME,
    S.MARKS ASC;